### ISSUE TITLE
Issue when activate Synonym group truncate

### ISSUE THREAD

**Issue by 777uliahshafar** [Ron89/thesaurus_query.vim#54] opened 2022-09-13 22:22 UTC
Hi, everyone. There is error message when I was trying to limit the synonym group. It happens when the word has many synonym for example 'place'. Alhoutgh it limited the word correctly and showed the correct result but it also showed red background error message. The error message unable to continue or pick the words.
The syntax I put in my vimrc that make it error is this, no matter I changes the number. `let g:tq_truncation_on_definition_num = 3` . 

Thanks.

![Screen Shot 2022-09-14 at 06 15 54](https://user-images.githubusercontent.com/67497706/190019464-06db65ab-1eb9-4357-8bbb-6ee0cb18f16c.png)

**Comment by Ron89** [comment] 2022-12-11 04:36
@777uliahshafar 
Sorry, didn't notice the notification.
The issue is caused by an unescaped \` symbol. I have fixed it. It should work as expected now.

**Comment by Ron89** [comment] 2022-12-11 04:36
I will close the issue. Feel free to re-open it if the issue still happen to you.

**Closed by Ron89** 2022-12-11 04:36 UTC
