### ISSUE TITLE
Buffer with this name already exists

### ISSUE THREAD

**Issue by elig0n** [Ron89/thesaurus_query.vim#29] opened 2018-05-23 07:41 UTC
after closing a Thesaurus query window with 'q' trying to run the query again for the same word results in 

>Error detected while processing function thesaurus_query#Thesaurus_Query_Lookup:
line   49:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/eligon/.vim/bundle/thesaurus_query.vim/autoload/thesaurus_query/thesaurus_query.py", line 380, in tq_generate_thesaurus_buffer
    vim_command('exec ":silent file thesaurus:\\\\ " . l:word_fname . "\\\\ (press\\\\ q\\\\ to\\\\ close\\\\ this\\\\ split.)"')
  File "/home/eligon/.vim/bundle/thesaurus_query.vim/autoload/thesaurus_query/tq_common_lib.py", line 120, in vim_command
    vim.command(command)
vim.error: Vim(file):E95: Buffer with this name already exists

**Comment by Ron89** [comment] 2018-05-23 10:30
It's strange. I managed to reproduce your issue on one instance, when `bufwinnr` output was behaving weird. But then after opening Vim in a different instance where `bufwinnr` is behaving as expected, I can no longer reproduce it.

Could you attach your environment? Like Vim version, and OS type? I have tried on both Mac and Linux 64bit.

**Comment by Ron89** [comment] 2018-05-23 10:32
@deathmaz , did you managed to reproduce his issue?

**Comment by deathmaz** [comment] 2018-05-23 10:40
Yes i did, i'm using `NVIM v0.2.2` on `Manjaro Linux 17.1.10 Hakoila`

**Comment by Ron89** [comment] 2018-05-25 18:45
Hi all, please try out the test branch to see if the issue is addressed. I have made some change and committed it to test branch. It should address the issue, but since I still couldn't reproduce it, I have to rely on your feedback before merge it to master branch.

From the error message itself, also my earlier experience in reproducing of the issue, it looks like error is triggered at line 380 of `autoload/thesaurus_query/thesaurus_query.py`.
This looks like the plugin failed to find the thesaurus buffer using pattern "^thesaurus: ", hence creating a new window, and then try to rename that new window to a name coincide with the original thesaurus buffer, triggering the "E95" issue.

The solution here is to avoid renaming a wrong buffer by try to entering the existing buffer in line 379 (commited file line 380). In this command, Vim shall split to the buffer with the target name, and only rename current buffer if the buffer do not exist. Actually I believe this is the originally intended logic. But I might have made a mistake modifying it some time ago.

Still, please try it out in test branch, in the plugin repo:
```
git fetch origin
git checkout testing
```
then try out the operation. If issue doesn't happen any more, let me know, then revert back to master branch, wait for me to merge. Thanks.

**Comment by deathmaz** [comment] 2018-05-26 07:09
Works perfectly fine on my end

**Comment by Ron89** [comment] 2018-05-26 08:14
Issue fixed on commit 859ee01.

**Closed by Ron89** 2018-05-26 08:14 UTC
